ALTER TABLE WEBPORTAL_DB_USER MODIFY COLUMN PASSWORD VARCHAR(32);
--修改USERNAME字段大小写敏感
ALTER TABLE WEBPORTAL_DB_USER MODIFY USERNAME VARCHAR(20) BINARY CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL;

CREATE TABLE `WEBPORTAL_AREA` (
  `ID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '地区表主键',
  `CODE` VARCHAR(30) DEFAULT NULL COMMENT '编号',
  `NAME` VARCHAR(20) DEFAULT NULL COMMENT '地区名称',
  `PARENT_ID` BIGINT(20) UNSIGNED COMMENT '父节点id',
  `DESCN` VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '描述',
  `DELETED` TINYINT(4) DEFAULT NULL,
  `CREATE_TIME` DATETIME DEFAULT NULL,
  `UPDATE_TIME` DATETIME DEFAULT NULL,
  `CREATE_USER` BIGINT(20) UNSIGNED DEFAULT NULL,
  `UPDATE_USER` BIGINT(20) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 COMMENT='地区表';

ALTER TABLE `WEBPORTAL_HCLUSTER` ADD AREA_ID BIGINT(20) UNSIGNED;

